### ISSUE TITLE
Sharing fetches across different namespaces

### ISSUE THREAD

**Issue by ricokahler** [JustSift/ReSift#10]
ReSift shares are essential features in order to keep consistency across our apps. However, I've noticed a problem with the current ReSift shares model and I'd like to propose a _non-breaking_ solution for this.

⚠️**This is a proposal** ⚠️

### Background

Let's say you have a fetch that represents a collection of things.

`moviesFetch.js`

```js
const { defineFetch } from 'resift';

const makeMoviesFetch = defineFetch({
  displayName: 'Get Movies',
  make: () => ({
    key: [],
    request: () => ({ http }) => http({
      method: 'GET',
      route: '/movies',
    }),
  }),
});
const moviesFetch = makeMoviesFetch();
export default moviesFetch;
```

And you also have another fetch that represent getting one of those things from that collection

`makeMovieFetch.js`

```js
import { defineFetch } from 'resift';

const makeMovieFetch = defineFetch({
  displayName: 'Get Movie',
  make: id => ({
    key: [],
    request: () => ({ http }) => http({
      method: 'GET',
      route: `/movies/${id}`,
    }),
  }),
});

export default makeMovieFetch;
```

And then you have one more fetch that updates a movie:

`makeUpdateMovieFetch.js`

```js
import { defineFetch } from 'resift';

const makeUpdateMovieFetch = defineFetch({
  displayName: 'Update Movie',
  make: id => ({
    key: [id],
    request: updatedMovie => ({ http }) => http({
      method: 'PUT',
      route: `/movies/${id}`,
      data: updatedMovie,
    }),
  }),
});
```

### The issue

The issue happens when you try to share all of these fetches. Each fetch is related because they come from the same collection, however, sharing them may lead to undesired results when pulling data.

When fetches are shared, they share the same store and this means that the `moviesFetch` (i.e. the list) will share the same state as the getting a single movie `makeMovieFetch` (i.e. an item from the list).

If you already have these fetches in use and you want to share the fetches to ensure consistency, then sharing the fetch would require changing the component's use of `useFetch` because the shape of the data coming back is different between `moviesFetch` and `makeMovieFetch`.

e.g.

before the share

```js
function Movie({ id }) {
  const movieFetch = makeMovieFetch(id);
  const [data] = useFetch(movieFetch);

  console.log(data); // { title: 'Paddington 2 } (just one movie)
}
```

after the share with movies

```js
function Movie({ id }) {
  const movieFetch = makeMovieFetch(id);
  const [data] = useFetch(movieFetch);

  console.log(data); // [{title: ...}, {title: ...}]; now it's a collection of movies??
}
```

### Root cause

I think the root cause of this problem is forcing shares to have the same shape.

## Solution

The solution to this problem is allow fetches that have different shapes to have separate state _but_ allow fetches to watch for changes from other namespaces.

The API I'm proposing will look like this:

`moviesFetch.js`

```js
import { defineFetch } from 'resift';

const makeMoviesFetch = defineFetch({
  displayName: 'Get Movies',
  share: {
    namespace: 'movieList',
    merge: {
      // movieList: (previousMovies, nextMovies) => nextMovies, // this is the default behavior 
      movieItem: (previousMovies, updatedMovie) => {
        const index = previousMovies.find(movie => movie.id === updatedMovie.id);
        const nextMovies = [
          ...previousMovies.slice(0, index),
         updatedMovie,
         ...previousMovies.slice(index + 1, previousMovies.length),
        ];
      },
    },
  },
  make: () => ({
    key: [],
    request: () => ({ http }) => http({
      method: 'GET',
      route: '/movies',
    }),
  })
});
```

`makeUpdateMovieFetch.js`

```js
import { defineFetch } from 'resift';

const makeUpdateMovieFetch = defineFetch({
  displayName: 'Update Movie';
  share: {
    namespace: 'movieItem',
    merge: {
      movieList: (previousMovie, movieList) =>
        movieList.find(movie => movie.id === previousMovie.id),
    },
  },
});
```

The idea here is that `share.merge` can now be an object and _react_ to changes in other namespace by using their namespace key in merge.

If the default behavior of the share is to be overridden then its own namespace key should be used as the merge key.

Let me know what y'all think! I think this could be very helpful for the Sift Lists feature on both web and mobile.

**Comment by JulesPatry** [comment]
@ricokahler, read through this. I am for this API change. This solution is a breaking change due to changing functionality of the `merge` property. How do you plan on deprecating the old version of it?

**Comment by ricokahler** [comment]
I was thinking we keep both APIs and depending on whether or not the merge property is an object or a function we do the current way or this proposed way.

**Comment by ricokahler** [comment]
I talked to @MPiccinato and @JulesPatry and they both approved this proposal so I'll probably begin work on this soon.

Any oppositions?

(cc @M-Jas @ccdwyer)
