### ISSUE TITLE
Updating the http request function to have the ability to add custom headers per each fetch request. 

### ISSUE THREAD

**Issue by JulesPatry** [JustSift/ReSift#104]
@pearlzhuzeng @ricokahler 
[`const data = await http(requestParams, httpOptions);`](https://github.com/JustSift/ReSift/blob/master/src/createHttpService/createHttpService.js#L103)

I have a use case where I need to add additional headers to a specific fetch. I'm going to write a PR that includes this. Below is an example of a fetch using this. 

I'm going to locally make something work and post my PR. 

```
http({
   method: "GET",
   route: "...",
   headers: { "foo": "bar"}
});
```

**Comment by ricokahler** [comment]
@JulesPatry you can already do this now using `req` which just lets you have access to the raw super agent request:

```js
http({
  method: "GET",
  route: "...",
  req: (req) => {
    req.set({ 'API-Key': 'foobar', Accept: 'application/json' })
  },
})
```

- [See here for resift docs](https://resift.org/docs/api/create-http-service)
- [See here for superagent docs](https://visionmedia.github.io/superagent/#setting-header-fields)

---

However, feel free to add this via a PR, I'll definitely review. I think it makes sense there too but if this is just a one-off, might not be worth it.
