### ISSUE TITLE
Resift will not render on Android React Native projects with hermes enabled.

### ISSUE THREAD

**Issue by JulesPatry** [JustSift/ReSift#105]
Hey Rico, letting you know about this issue and in no way do I feel you are responsible for fixing this. In the short term, Sift will disable hermes because we do not debug from android devices very often.

### The Issue
When resift library is import'ed on an android react native application with hermes enabled, the application will error out saying **"React Native Hermes: undefined is not a function js engine: hermes"**

Seems like Hermes does not want to render the build file from resift. And due to the entire resift library being on one file, it is rather challenging to quickly see where in the build index.js file is there not a function defined.

### What is Hermes
_Hermes is an open-source JavaScript engine optimized for running React Native apps on Android. For many apps, enabling Hermes will result in improved start-up time, decreased memory usage, and smaller app size. At this time Hermes is an opt-in React Native feature, and this guide explains how to enable it._

https://reactnative.dev/docs/hermes

**Comment by ricokahler** [comment]
Let's set up some time to debug this. I've been wanting to change ReSift's build to use rollup instead of webpack because it's more friendly to different environments. Let me know!
