### ISSUE TITLE
Set a default for the `key` property on the make function in `defineFetch`

### ISSUE THREAD

**Issue by JulesPatry** [JustSift/ReSift#14]
```
export default defineFetch({
  displayName: 'Get People from listId',
  make: (listId: string) => ({
    key: [listId],
    request: () => ({ http }) =>
      return http({
        method: 'GET',
        route: `/list/${listId}/members/`,
      }),
  }),
});
```

From all the times I've used Resift, I have never had to deviate from what I passed into the make value, to then into the key value. 

To keep things more simple for Resift, I purpose default the key value to be the arguments passed into the make function. If there needs to be an override, be explicit and declare the key value to be something unique.

**Comment by M-Jas** [comment]
@JulesPatry so you don't want to use `key` anymore at all? Just let it default through? Why would this make it more simple? What happens if you are passing nothing into the make but you want to set a specific key?
