### ISSUE TITLE
Proposal: Guard

### ISSUE THREAD

**Issue by ricokahler** [JustSift/ReSift#20]
One of the hardest problems about data fetching in components is dealing with null values gracefully.

I originally thought suspense would be our silver bullet to everything against falsy data checks but that's not exactly the case. The issue with Suspense is that if a certain data requirement is not met, the whole component will be blocked from rendering. This not ideal in situations where you rely on a certain part of the component to be mounted for animations or layout structure and size.

For example, let's say you have a material-ui `Drawer` component. This component should always be mounted regardless if there is data ready because of the animation in and the animation out. We shouldn't block the whole component because then we wouldn't be able to see the drawer animate in.

You could argue that we should just split up the components so that there is a suspending part and a non-suspending part but, imo, that division feels slightly clunky.

e.g.

```js
import React from 'react';
import { useDispatch } from 'resift';

function SuspendingComponent({ exampleFetch }) {
  const dispatch = useDispatch();
  const data = useSuspendingFetch(exampleFetch, () => dispatch(exampleFetch()));

  return <div>{data.stuff}</div>
}

function NonSuspendingComponent({ id }) {
  const exampleFetch = makeExampleFetch(id);
  
  return <Drawer>
    <Suspense fallback={<CircularProgress />}>
      <SuspendingComponent />
    </Suspense>
  </Drawer>;
}
```

It feels especially clunky having to pass some sort of prop down to the suspending component.

---

Anyway, I don't think that'll work so let's try something else.

This issue proposes: **`useGuard`**

`useGuard` is a custom hook that takes in a fetch and returns a component that takes in a render prop. That render prop will only be invoked when there is data available and will provide the data as its argument.

e.g.

```js
function UseGuardExample({ id }) {
  const exampleFetch = makeExampleFetch(id);
  const status = useFetch(exampleFetch)[1];
  const Guard = useGuard(exampleFetch);

  return <Drawer>
    {isLoading(status) && <CircularProgress />}
    <Guard>{data => <div>{data.stuff}</div>}</Guard>
  </Drawer>;
}
```

---

Implementation:

```js
import { useMemo } from "react";
import { useFetch, isNormal } from "resift";

function useGuard(fetch) {
  return useMemo(() => {
    function Guard({ children }) {
      const [data, status] = useFetch(fetch);
      return isNormal(status) && children(data);
    }

    return Guard;
  }, [fetch]);
}

export default useGuard;
```

**Comment by pearlzhuzeng** [comment]
This is neat!

**Comment by ricokahler** [comment]
We gon do this instead

```js
import {isNormal, useFetch} from 'resift';
function Guard({fetch, children}) {
  const [data, status] = useFetch(fetch);
  return isNormal(status) && children(data);
}
```
